reviewers:
  # The default reviewers
  groups:
    gher:
      - Kimthanh11
      - NguyenLe1605
      - vinhDev3006
      - TomNewbie
      - MinhTran1506

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: true
