version: '3.1'

services:
  tensorflow:
    container_name: tfserving
    image: 'tensorflow/serving'
    volumes:
      - './models/LSTM_1_model_saved_model:/models/lstm'
    ports:
      - '8501:8501'
    environment:
      - MODEL_NAME=lstm
  gmanbus:
    container_name: gmanbus
    build: ./backend
    ports:
      - '8000:8000'
