version: '3.1'

services:
  predict:
    container_name: predict
    build: ./backend/prediction
    ports:
      - '5000:5000'
  gmanbus:
    container_name: gmanbus
    build: ./backend
    ports:
      - '8000:8000'
