on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Print working directory
        run: pwd

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Print working directory
        run: pwd
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
