name: Change detection

on:
  workflow_dispatch:
  # pull_request:
  # push:
  #   branches:
  #     - main
  #     - release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.head_ref ||  github.run_id }}
  cancel-in-progress: true

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-20.04
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 20
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            rust-server:
              - 'backend/src/**'
            frontend:
              - 'frontend/**'
            prediction-server:
              - 'backend/prediction/**'
            streaming-server:
              - 'backend/streaming/**'
            data:
              - 'Data/**'
              - 'archive/**'
            test:
              - 'test/**'
  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend== 'true' }}
    uses: ./.github/workflows/frontend.yml
