name: Change detection

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.head_ref ||  github.run_id }}
  cancel-in-progress: true

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-20.04
    outputs:
      rust-server: ${{ steps.filter.outputs.rust-server }}
      streaming-server: ${{ steps.filter.outputs.streaming-server }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 20
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            rust-server:
              - 'backend/src/**'
            frontend:
              - 'frontend/**'
            prediction-server:
              - 'backend/prediction/**'
            streaming-server:
              - 'backend/streaming/**'
            data:
              - 'Data/**'
              - 'archive/**'
            test:
              - 'test/**'
  # backend:
  #   needs: changes
  #   if: ${{ needs.changes.outputs.rust-server== 'true' }}
  #   uses: ./.github/workflows/backend.yml
  # streaming-server:
  #   needs: changes
  #   if: ${{ needs.changes.outputs.streaming-server== 'true' }}
  #   uses: ./.github/workflows/streaming-server.yml
  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend== 'true' }}
    uses: ./.github/workflows/frontend.yml
