name: Quality Katalon Healthcare

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.head_ref ||  github.run_id }}
  cancel-in-progress: true

jobs:
  changes:
    uses: ./.github/workflows/change-detect.yml

  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    uses: ./.github/workflows/frontend.yml
    secrets:
      github-token: ${{ secrets.THO_GITHUB_TOKEN }}
