name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/labeler@v4.3.0
        with:
          configuration-path: ".github/labeler_tag.yml"
          sync-labels: "true"
