name: "My workflow"
on:
  - pull_request_target

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            data:
              - 'Data/**'

  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - id: label-the-PR
        uses: actions/labeler@v4

      - id: run-frontend-tests
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        run: |
          echo "Running frontend tests..."
