name: Deploy to Streaming Server

on:
  #   push:
  #     branches:
  #       - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: streaming-server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Add support for more platforms with QEMU (optional)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name:${{ github.run_number }}-${{ github.sha }}

      - name: SSH into Remote Server and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STREAMING_SERVER_HOST }}
          key: ${{ secrets.STREAMING_SERVER_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest
            docker run -d --name your-container-name -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest
